//
//  PetsInteractor.swift
//  patmeapp
//
//  Created by Juan Camilo on 9/02/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PetsBusinessLogic
{
  func doSomething(request: Pets.Something.Request)
}

protocol PetsDataStore
{
  //var name: String { get set }
}

class PetsInteractor: PetsBusinessLogic, PetsDataStore
{
  var presenter: PetsPresentationLogic?
  var worker: PetsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Pets.Something.Request)
  {
    worker = PetsWorker()
    worker?.doSomeWork()
    
    let response = Pets.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
