//
//  PetsPresenter.swift
//  patmeapp
//
//  Created by Juan Camilo on 9/02/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PetsPresentationLogic
{
  func presentSomething(response: Pets.Something.Response)
}

class PetsPresenter: PetsPresentationLogic
{
  weak var viewController: PetsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Pets.Something.Response)
  {
    let viewModel = Pets.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
