//
//  StartWelcomeViewController.swift
//  PatMe
//
//  Created by Juan Camilo on 14/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Auth0

protocol StartWelcomeDisplayLogic: AnyObject
{
  func displaySomething(viewModel: StartWelcome.Something.ViewModel)
}

class StartWelcomeViewController: UIViewController, StartWelcomeDisplayLogic
{
  var interactor: StartWelcomeBusinessLogic?
  var router: (NSObjectProtocol & StartWelcomeRoutingLogic & StartWelcomeDataPassing)?
 
    var petObject: PetModel!
    @IBOutlet weak var logOut: UIButton!
    @IBOutlet weak var TitleLbl: UILabel!
    @IBOutlet weak var dogBtn: UIButton!
    @IBOutlet weak var catBtn: UIButton!
    @IBOutlet weak var horseBtn: UIButton!
    @IBOutlet weak var rabbitBtn: UIButton!
    @IBOutlet weak var birdBtn: UIButton!
    @IBOutlet weak var otherBtn: UIButton!
    
    @IBOutlet weak var dogLbl: UILabel!
    @IBOutlet weak var catLbl: UILabel!
    
    @IBOutlet weak var otherLbl: UILabel!
    @IBOutlet weak var birdLbl: UILabel!
    @IBOutlet weak var rabbitLbl: UILabel!
    @IBOutlet weak var horseLbl: UILabel!
    // MARK: Object lifecycle
  
 
    
 
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = StartWelcomeInteractor()
    let presenter = StartWelcomePresenter()
    let router = StartWelcomeRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
      TitleLbl.text = NSLocalizedString("start_view_title_txt_1", comment: "")
      
      dogLbl.text = NSLocalizedString("Dog", comment: "")
      catLbl.text = NSLocalizedString("Cat", comment: "")
          birdLbl.text = NSLocalizedString("Bird", comment: "")
      horseLbl.text = NSLocalizedString("Horse", comment: "")
      rabbitLbl.text = NSLocalizedString("Rabbit", comment: "")
      otherLbl.text = NSLocalizedString("Other", comment: "")
      
      
      
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = StartWelcome.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: StartWelcome.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
    @IBAction func onBackBtn(_ sender: Any) {
        let storyboard = UIStoryboard (name: "Main", bundle: nil)
               let vc = storyboard.instantiateViewController(withIdentifier: "LoginAuth0ViewController")as? LoginAuth0ViewController

               // you can set any value stored in the destination VC her
        self.navigationController?.pushViewController(vc!, animated: true)
        
    }
    @IBAction func onLogOut(_ sender: Any) {
        
        Auth0
            .webAuth()
            .useEphemeralSession()
            .clearSession(federated: true) { result in
                if result {
                    // Session cleared
                    print("Log Out")
                    DispatchQueue.main.async {
                        let storyboard = UIStoryboard (name: "Main", bundle: nil)
                               let vc = storyboard.instantiateViewController(withIdentifier: "LoginAuth0ViewController")as? LoginAuth0ViewController

                               // you can set any value stored in the destination VC here
                      
                        self.navigationController?.pushViewController(vc!, animated: true)
                       
                    }
                }
            }
    }
    @IBAction func OnOtherBtn(_ sender: Any) {
        let storyboard = UIStoryboard (name: "Main", bundle: nil)
        let vc = storyboard.instantiateViewController(withIdentifier: "OtherViewController")as? OtherViewController
       
        self.navigationController?.pushViewController(vc!, animated: true)
    }
    
    @IBAction func onDogBtn(_ sender: Any) {
        sendNextScreen(specie: MainSpeciesEnum.dog)
        
    }
    
    @IBAction func onCatBtn(_ sender: Any) {
        sendNextScreen(specie: MainSpeciesEnum.cat)
    }
    
    @IBAction func onHorseBtn(_ sender: Any) {
        sendNextScreen(specie: MainSpeciesEnum.horse)
    }
    
    @IBAction func onRabbitBtn(_ sender: Any) {
        sendNextScreen(specie: MainSpeciesEnum.rabbit)
    }
    
    @IBAction func onBirdBtn(_ sender: Any) {
        sendNextScreen(specie: MainSpeciesEnum.bird)
        
    }
    func sendNextScreen(specie: MainSpeciesEnum){
        let storyboard = UIStoryboard (name: "Main", bundle: nil)
        let vc = storyboard.instantiateViewController(withIdentifier: "RegisterPetViewController")as? RegisterPetViewController
        
        // you can set any value stored in the destination VC here
        petObject = PetModel(name: "",specie: specie)
        vc!.petObject =  petObject
       
        self.navigationController?.pushViewController(vc!, animated: true)
    
    }
    
}
