//
//  StartWelcomeInteractor.swift
//  PatMe
//
//  Created by Juan Camilo on 14/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StartWelcomeBusinessLogic
{
  func doSomething(request: StartWelcome.Something.Request)
}

protocol StartWelcomeDataStore
{
  //var name: String { get set }
}

class StartWelcomeInteractor: StartWelcomeBusinessLogic, StartWelcomeDataStore
{
  var presenter: StartWelcomePresentationLogic?
  var worker: StartWelcomeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: StartWelcome.Something.Request)
  {
    worker = StartWelcomeWorker()
    worker?.doSomeWork()
    
    let response = StartWelcome.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
