//
//  RegisterPetInteractor.swift
//  patmeapp
//
//  Created by Juan Camilo on 5/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterPetBusinessLogic
{
  func doSomething(request: RegisterPet.Something.Request)
}

protocol RegisterPetDataStore
{
  //var name: String { get set }
}

class RegisterPetInteractor: RegisterPetBusinessLogic, RegisterPetDataStore
{
  var presenter: RegisterPetPresentationLogic?
  var worker: RegisterPetWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: RegisterPet.Something.Request)
  {
    worker = RegisterPetWorker()
    worker?.doSomeWork()
    
    let response = RegisterPet.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
