//
//  RegisterPetRouter.swift
//  patmeapp
//
//  Created by Juan Camilo on 5/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RegisterPetRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol RegisterPetDataPassing
{
  var dataStore: RegisterPetDataStore? { get }
}

class RegisterPetRouter: NSObject, RegisterPetRoutingLogic, RegisterPetDataPassing
{
  weak var viewController: RegisterPetViewController?
  var dataStore: RegisterPetDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: RegisterPetViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: RegisterPetDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
