//
//  RegisterPetPresenter.swift
//  patmeapp
//
//  Created by Juan Camilo on 5/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterPetPresentationLogic
{
  func presentSomething(response: RegisterPet.Something.Response)
}

class RegisterPetPresenter: RegisterPetPresentationLogic
{
  weak var viewController: RegisterPetDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: RegisterPet.Something.Response)
  {
    let viewModel = RegisterPet.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
