//
//  TestInteractor.swift
//  patmeapp
//
//  Created by Juan Camilo on 26/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TestBusinessLogic
{
  func doSomething(request: Test.Something.Request)
}

protocol TestDataStore
{
  //var name: String { get set }
}

class TestInteractor: TestBusinessLogic, TestDataStore
{
  var presenter: TestPresentationLogic?
  var worker: TestWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Test.Something.Request)
  {
    worker = TestWorker()
    worker?.doSomeWork()
    
    let response = Test.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
