//
//  NeuteredPresenter.swift
//  patmeapp
//
//  Created by Juan Camilo on 14/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NeuteredPresentationLogic
{
  func presentSomething(response: Neutered.Something.Response)
}

class NeuteredPresenter: NeuteredPresentationLogic
{
  weak var viewController: NeuteredDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Neutered.Something.Response)
  {
    let viewModel = Neutered.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
