//
//  OtherInteractor.swift
//  patmeapp
//
//  Created by Juan Camilo on 28/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OtherBusinessLogic
{
  func doSomething(request: Other.Something.Request)
}

protocol OtherDataStore
{
  //var name: String { get set }
}

class OtherInteractor: OtherBusinessLogic, OtherDataStore
{
  var presenter: OtherPresentationLogic?
  var worker: OtherWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Other.Something.Request)
  {
    worker = OtherWorker()
    worker?.doSomeWork()
    
    let response = Other.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
