//
//  OtherPresenter.swift
//  patmeapp
//
//  Created by Juan Camilo on 28/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OtherPresentationLogic
{
  func presentSomething(response: Other.Something.Response)
}

class OtherPresenter: OtherPresentationLogic
{
  weak var viewController: OtherDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Other.Something.Response)
  {
    let viewModel = Other.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
