//
//  GenereViewControllerViewController.swift
//  patmeapp
//
//  Created by Juan Camilo on 14/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


protocol GenereViewControllerDisplayLogic: AnyObject
{
  func displaySomething(viewModel: GenereViewController.Something.ViewModel)
}

class GenereViewControllerViewController: ResourcesViewController, GenereViewControllerDisplayLogic
{
  var interactor: GenereViewControllerBusinessLogic?
    @IBOutlet weak var titleLbl: UILabel!
    @IBOutlet weak var backBtn: UIButton!
    @IBOutlet weak var maleBtn: UIButton!
    @IBOutlet weak var femaleBtn: UIButton!
    @IBOutlet weak var maleLbl: UILabel!
    @IBOutlet weak var femaleLbl: UILabel!
    @IBOutlet weak var otherBtn: UIButton!
    @IBOutlet weak var otherLbl: UILabel!
    @IBOutlet weak var addLater: UIButton!
  
    var genere = String()
    var petObject: PetModel!
    var router: (NSObjectProtocol & GenereViewControllerRoutingLogic & GenereViewControllerDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = GenereViewControllerInteractor()
    let presenter = GenereViewControllerPresenter()
    let router = GenereViewControllerRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
      titleLbl.text = NSLocalizedString("genere_view_title_txt_1", comment: "") + petObject.name + "?"
      maleLbl.text = NSLocalizedString("genere_view_title_txt_2", comment: "")
      femaleLbl.text = NSLocalizedString("genere_view_title_txt_3", comment: "")
      otherLbl.text = NSLocalizedString("genere_view_title_txt_4", comment: "")
      addLater.setTitle(NSLocalizedString("genere_view_title_btn_1", comment: ""), for: .normal)
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = GenereViewController.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: GenereViewController.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
    
    @IBAction func onMaleBtn(_ sender: Any) {
        sendNextScreen(genere: GenderEnum.male)
    }
    
    @IBAction func onFemaleBtn(_ sender: Any) {
        sendNextScreen(genere: GenderEnum.female)
        
    }
    
    @IBAction func onLater(_ sender: Any) {
        sendNextScreen(genere: nil)
        
    }
    @IBAction func onOtherBtn(_ sender: Any) {
       
        sendNextScreen(genere: GenderEnum.other)
        // you can set any value stored in the destination VC here

    }
    func sendNextScreen(genere: GenderEnum?){
        let storyboard = UIStoryboard (name: "Main", bundle: nil)
        let vc = storyboard.instantiateViewController(withIdentifier: "NeuteredViewController")as? NeuteredViewController
        petObject.gender = genere
        // you can set any value stored in
        vc!.petObject =  petObject
       
        self.navigationController?.pushViewController(vc!, animated: true)
    
    }
    
    @IBAction func onBackBtn(_ sender: Any) {
        let storyboard = UIStoryboard (name: "Main", bundle: nil)
        let vc = storyboard.instantiateViewController(withIdentifier: "RegisterPetViewController")as? RegisterPetViewController
        
        // you can set any value stored in the destination VC here
       
        vc!.petObject =  petObject
       
    
        self.navigationController?.pushViewController(vc!, animated: true)
        
    }
    
}
