//
//  GenereViewControllerPresenter.swift
//  patmeapp
//
//  Created by Juan Camilo on 14/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GenereViewControllerPresentationLogic
{
  func presentSomething(response: GenereViewController.Something.Response)
}

class GenereViewControllerPresenter: GenereViewControllerPresentationLogic
{
  weak var viewController: GenereViewControllerDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: GenereViewController.Something.Response)
  {
    let viewModel = GenereViewController.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
