//
//  SuccesRegisterInteractor.swift
//  patmeapp
//
//  Created by Juan Camilo on 19/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SuccesRegisterBusinessLogic
{
  func doSomething(request: SuccesRegister.Something.Request)
}

protocol SuccesRegisterDataStore
{
  //var name: String { get set }
}

class SuccesRegisterInteractor: SuccesRegisterBusinessLogic, SuccesRegisterDataStore
{
  var presenter: SuccesRegisterPresentationLogic?
  var worker: SuccesRegisterWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SuccesRegister.Something.Request)
  {
    worker = SuccesRegisterWorker()
    worker?.doSomeWork()
    
    let response = SuccesRegister.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
