//
//  OnBoardingPresenter.swift
//  PatMe
//
//  Created by Juan Camilo on 3/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OnBoardingPresentationLogic
{
  func presentSomething(response: OnBoarding.Something.Response)
}

class OnBoardingPresenter: OnBoardingPresentationLogic
{
  weak var viewController: OnBoardingDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: OnBoarding.Something.Response)
  {
    let viewModel = OnBoarding.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
