//
//  OnBoardingInteractor.swift
//  PatMe
//
//  Created by Juan Camilo on 3/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OnBoardingBusinessLogic
{
  func doSomething(request: OnBoarding.Something.Request)
}

protocol OnBoardingDataStore
{
  //var name: String { get set }
}

class OnBoardingInteractor: OnBoardingBusinessLogic, OnBoardingDataStore
{
  var presenter: OnBoardingPresentationLogic?
  var worker: OnBoardingWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: OnBoarding.Something.Request)
  {
    worker = OnBoardingWorker()
    worker?.doSomeWork()
    
    let response = OnBoarding.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
