//
//  RegisterPetPicturePresenter.swift
//  patmeapp
//
//  Created by Juan Camilo on 17/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterPetPicturePresentationLogic
{
  func presentSomething(response: RegisterPetPicture.Something.Response)
}

class RegisterPetPicturePresenter: RegisterPetPicturePresentationLogic
{
  weak var viewController: RegisterPetPictureDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: RegisterPetPicture.Something.Response)
  {
    let viewModel = RegisterPetPicture.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
