//
//  RegisterPetPictureInteractor.swift
//  patmeapp
//
//  Created by Juan Camilo on 17/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterPetPictureBusinessLogic
{
  func doSomething(request: RegisterPetPicture.Something.Request)
}

protocol RegisterPetPictureDataStore
{
  //var name: String { get set }
}

class RegisterPetPictureInteractor: RegisterPetPictureBusinessLogic, RegisterPetPictureDataStore
{
  var presenter: RegisterPetPicturePresentationLogic?
  var worker: RegisterPetPictureWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: RegisterPetPicture.Something.Request)
  {
    worker = RegisterPetPictureWorker()
    worker?.doSomeWork()
    
    let response = RegisterPetPicture.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
