//
//  BirthdayInteractor.swift
//  patmeapp
//
//  Created by Juan Camilo on 19/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BirthdayBusinessLogic
{
  func doSomething(request: Birthday.Something.Request)
}

protocol BirthdayDataStore
{
  //var name: String { get set }
}

class BirthdayInteractor: BirthdayBusinessLogic, BirthdayDataStore
{
  var presenter: BirthdayPresentationLogic?
  var worker: BirthdayWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Birthday.Something.Request)
  {
    worker = BirthdayWorker()
    worker?.doSomeWork()
    
    let response = Birthday.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
