//
//  BirthdayPresenter.swift
//  patmeapp
//
//  Created by Juan Camilo on 19/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BirthdayPresentationLogic
{
  func presentSomething(response: Birthday.Something.Response)
}

class BirthdayPresenter: BirthdayPresentationLogic
{
  weak var viewController: BirthdayDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Birthday.Something.Response)
  {
    let viewModel = Birthday.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
