//
//  TestMaterialPresenter.swift
//  patmeapp
//
//  Created by Juan Camilo on 21/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TestMaterialPresentationLogic
{
  func presentSomething(response: TestMaterial.Something.Response)
}

class TestMaterialPresenter: TestMaterialPresentationLogic
{
  weak var viewController: TestMaterialDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: TestMaterial.Something.Response)
  {
    let viewModel = TestMaterial.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
