//
//  TestMaterialInteractor.swift
//  patmeapp
//
//  Created by Juan Camilo on 21/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TestMaterialBusinessLogic
{
  func doSomething(request: TestMaterial.Something.Request)
}

protocol TestMaterialDataStore
{
  //var name: String { get set }
}

class TestMaterialInteractor: TestMaterialBusinessLogic, TestMaterialDataStore
{
  var presenter: TestMaterialPresentationLogic?
  var worker: TestMaterialWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: TestMaterial.Something.Request)
  {
    worker = TestMaterialWorker()
    worker?.doSomeWork()
    
    let response = TestMaterial.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
