//
//  BreedInteractor.swift
//  patmeapp
//
//  Created by Juan Camilo on 18/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BreedBusinessLogic
{
  func doSomething(request: Breed.Something.Request)
}

protocol BreedDataStore
{
  //var name: String { get set }
}

class BreedInteractor: BreedBusinessLogic, BreedDataStore
{
  var presenter: BreedPresentationLogic?
  var worker: BreedWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Breed.Something.Request)
  {
    worker = BreedWorker()
    worker?.doSomeWork()
    
    let response = Breed.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
