//
//  BreedPresenter.swift
//  patmeapp
//
//  Created by Juan Camilo on 18/01/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BreedPresentationLogic
{
  func presentSomething(response: Breed.Something.Response)
}

class BreedPresenter: BreedPresentationLogic
{
  weak var viewController: BreedDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Breed.Something.Response)
  {
    let viewModel = Breed.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
